services:
  movies-spark-hadoop:
    build: .
    image: movies-spark-hadoop:local
    container_name: movies-project
    hostname: localhost
    ports:
      - "9870:9870"
      - "8088:8088"
      - "8042:8042"
      - "9864:9864"
      - "4040:4040"
      - "8050:8050"   # Dashboard
    volumes:
      - ./films:/app/films 
      - .:/app
      - ./data:/app/data
      - ./scripts:/app/scripts
      - ./config:/app/config
      - ./kafka_2.13-2.8.1:/opt/kafka_2.13-2.8.1
    working_dir: /app
    command: ["/bin/bash", "-c", "/app/scripts/start_all.sh"]