
services:
  movies-spark-hadoop:
    image: movies-spark-hadoop:local
    container_name: movies-project
    hostname: localhost
    ports:
      - "9870:9870"
      - "8088:8088"
      - "8042:8042"
      - "9864:9864"
      - "4040:4040"
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
      - ./config:/app/config
    working_dir: /ap
    command: /bin/bash -c "/app/scripts/startup_project.sh"
