
services:
  movies-spark-hadoop:
    image: movies-spark-hadoop:local
    container_name: movies-project
    hostname: localhost
    ports:
      - "9870:9870"   # HDFS NameNode
      - "8088:8088"   # YARN ResourceManager
      - "8042:8042"   # YARN NodeManager
      - "9864:9864"   # HDFS DataNode
      - "4040:4040"   # Spark UI
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
      - ./config:/app/config
    working_dir: /app
    command: /bin/bash -c "/app/scripts/startup_project.sh"